// src/components/ChatBot.svelte
<script>
    let messages = [];
    let input = '';

    function sendMessage() {
        messages = [...messages, { text: input, sender: 'user' }];
        input = '';
        setTimeout(() => {
            messages = [...messages, { text: 'Bot Reply', sender: 'bot' }];
        }, 1000);
    }
</script>

<div class="chat-container">
    <div class="chat-header">ChatBot</div>
    <div class="chat-messages">
        {#each messages as msg, i}
            <div class={msg.sender === 'user' ? 'user-message' : 'bot-message'}>{msg.text}</div>
        {/each}
    </div>
    <div class="chat-input">
        <input bind:value={input} placeholder="Type a message..." />
        <button on:click={sendMessage}>Send</button>
    </div>
</div>

<style>
/* Add Svelte-specific styling */
</style>

// src/components/ChatBot.jsx
import React, { useState } from 'react';
import ReactDOM from 'react-dom';

const ChatBot = () => {
    const [messages, setMessages] = useState([]);
    const [input, setInput] = useState('');

    const sendMessage = () => {
        setMessages([...messages, { text: input, sender: 'user' }]);
        setInput('');
        setTimeout(() => {
            setMessages([...messages, { text: input, sender: 'user' }, { text: 'Bot Reply', sender: 'bot' }]);
        }, 1000);
    };

    return (
        <div className="chat-container">
            <div className="chat-header">ChatBot</div>
            <div className="chat-messages">
                {messages.map((msg, index) => (
                    <div key={index} className={msg.sender === 'user' ? 'user-message' : 'bot-message'}>
                        {msg.text}
                    </div>
                ))}
            </div>
            <div className="chat-input">
                <input value={input} onChange={(e) => setInput(e.target.value)} placeholder="Type a message..." />
                <button onClick={sendMessage}>Send</button>
            </div>
        </div>
    );
};

const ReactChatBot = (container) => ReactDOM.render(<ChatBot />, container);

export default ReactChatBot;
